[.githooks/pre-push] dev@carlosnunez.me  |  Use `make` instead.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -11,20 +11,12 @@ then
     exit 1
   fi
 
-  for command in "bundle install --quiet" "bundle exec rake test"
-  do
-    if ! docker run -v $PWD:/work \
-      -v $PWD/.gem:/root/.gem \
-      -w /work \
-      -e GEM_HOME=/root/.gem \
-      -e BUNDLE_PATH=/root/.gem \
-      carlosonunez/ruby-rake-alpine:2.4.2 "$command"
-    then
-      echo "ERROR: Tests failed! If this is intentional, include \"[FORCE COMMIT]\" \
-  to the beginning of your commit message." >&2
-      exit 1
-    fi
-  done
+  if ! make test
+  then
+    echo "ERROR: Tests failed! If this is intentional, include \"[FORCE COMMIT]\" \
+      to the beginning of your commit message." >&2
+    exit 1
+  fi
 fi
 
 echo "INFO: All tests passed! Continuing push."
